from __future__ import annotations

from copy import deepcopy
from datetime import date, datetime, timezone
import json
from pathlib import Path
from typing import Any

import streamlit as st

BASE_DIR = Path(__file__).resolve().parent
RUNTIME_SNAPSHOT_DIR = BASE_DIR / "data" / "cache"
PREBUILT_SNAPSHOT_DIR = BASE_DIR / "data" / "snapshots"
PREBUILT_SNAPSHOT_FILE = PREBUILT_SNAPSHOT_DIR / "current_full.json"


def _safe_date(target_date: str | None) -> str:
    return str(target_date or date.today().isoformat()).replace("/", "-")


def _runtime_snapshot_path(target_date: str | None, mode: str) -> Path:
    return RUNTIME_SNAPSHOT_DIR / f"board_{_safe_date(target_date)}_{mode}.json"


def _valid_board(payload: Any, target_date: str | None = None) -> bool:
    if not isinstance(payload, dict) or not payload.get("rankings"):
        return False
    requested = _safe_date(target_date)
    board_date = _safe_date(str(payload.get("date") or ""))
    return not target_date or requested == board_date


def _read_json(path: Path) -> dict[str, Any] | None:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    return payload if isinstance(payload, dict) else None


@st.cache_data(ttl=300, show_spinner=False)
def _read_prebuilt_snapshot(target_date: str | None) -> dict[str, Any] | None:
    """Read the board generated by GitHub Actions.

    This file is committed to the repository, so it survives Streamlit sleep,
    restarts, and redeploys. Reading it takes milliseconds and avoids dozens
    of API requests during a visitor's page load.
    """
    payload = _read_json(PREBUILT_SNAPSHOT_FILE)
    if not _valid_board(payload, target_date):
        return None

    prepared = dict(payload or {})
    prepared["fast_start"] = True
    prepared["snapshot_status"] = "prepared daily snapshot"
    prepared["snapshot_file"] = str(PREBUILT_SNAPSHOT_FILE)
    prepared.setdefault("snapshot_generated_at", prepared.get("updated_at", ""))
    prepared.setdefault("data_sources", {})["Fast Start"] = "prepared"
    return prepared


def snapshot_available(target_date: str | None = None) -> bool:
    return _read_prebuilt_snapshot(target_date) is not None


def _read_runtime_snapshot(
    target_date: str | None,
    mode: str,
    max_age_seconds: int,
) -> dict[str, Any] | None:
    path = _runtime_snapshot_path(target_date, mode)
    try:
        age = datetime.now(timezone.utc).timestamp() - path.stat().st_mtime
        if age > max_age_seconds:
            return None
        payload = _read_json(path)
        return payload if _valid_board(payload, target_date) else None
    except OSError:
        return None


def _write_runtime_snapshot(
    target_date: str | None,
    mode: str,
    payload: dict[str, Any],
) -> None:
    try:
        RUNTIME_SNAPSHOT_DIR.mkdir(parents=True, exist_ok=True)
        path = _runtime_snapshot_path(target_date, mode)
        temporary = path.with_suffix(".tmp")
        temporary.write_text(json.dumps(payload, default=str), encoding="utf-8")
        temporary.replace(path)
    except (OSError, TypeError, ValueError):
        pass


@st.cache_data(ttl=7200, show_spinner=False)
def _load_model_base(target_date: str | None = None) -> dict[str, Any]:
    """Live fallback for dates that do not have a prepared snapshot."""
    cached = _read_runtime_snapshot(target_date, "base", 60 * 60)
    if cached:
        cached["snapshot_status"] = "runtime disk cache"
        return cached

    from model import get_home_run_rankings

    payload = get_home_run_rankings(target_date=target_date)
    _write_runtime_snapshot(target_date, "base", payload)
    return payload


@st.cache_data(ttl=1800, show_spinner=False)
def _load_weather_board(target_date: str | None = None) -> dict[str, Any]:
    cached = _read_runtime_snapshot(target_date, "weather", 20 * 60)
    if cached:
        cached["snapshot_status"] = "weather runtime cache"
        return cached

    from services.weather import enrich_board_weather

    payload = enrich_board_weather(deepcopy(_load_model_base(target_date)))
    _write_runtime_snapshot(target_date, "weather", payload)
    return payload


@st.cache_data(ttl=600, show_spinner=False)
def _load_odds_board(
    target_date: str | None = None,
    include_weather: bool = False,
) -> dict[str, Any]:
    mode = "odds_weather" if include_weather else "odds"
    cached = _read_runtime_snapshot(target_date, mode, 8 * 60)
    if cached:
        cached["snapshot_status"] = "odds runtime cache"
        return cached

    from services.odds import enrich_board_odds

    base = (
        _load_weather_board(target_date)
        if include_weather
        else deepcopy(_load_model_base(target_date))
    )
    payload = enrich_board_odds(deepcopy(base))
    _write_runtime_snapshot(target_date, mode, payload)
    return payload


def load_board(
    target_date: str | None = None,
    *,
    include_weather: bool = False,
    include_odds: bool = False,
    prefer_prebuilt: bool = True,
) -> dict[str, Any]:
    """Return a prepared board immediately, with live APIs as a fallback.

    The scheduled GitHub workflow creates ``data/snapshots/current_full.json``.
    Every page can use that already-enriched board, so Streamlit does not rebuild
    player history, Statcast, pitchers, weather, and odds for each visitor.
    """
    if prefer_prebuilt:
        prepared = _read_prebuilt_snapshot(target_date)
        if prepared is not None:
            return deepcopy(prepared)

    if include_odds:
        return deepcopy(_load_odds_board(target_date, include_weather))
    if include_weather:
        return deepcopy(_load_weather_board(target_date))
    return deepcopy(_load_model_base(target_date))


def _clear_all() -> None:
    _load_odds_board.clear()
    _load_weather_board.clear()
    _load_model_base.clear()
    _read_prebuilt_snapshot.clear()


load_board.clear = _clear_all  # type: ignore[attr-defined]


def empty_board(
    error: Exception | None = None,
    target_date: str | None = None,
) -> dict[str, Any]:
    return {
        "date": target_date or date.today().isoformat(),
        "updated_at": "",
        "games": 0,
        "games_meta": [],
        "teams": [],
        "rankings": [],
        "data_sources": {},
        "fast_start": False,
        "error": str(error) if error else "",
    }
